{
 "title": "BMP_CLICKHOUSE",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Flapped router",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "bmp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select ts, action,name,ip_addr,term_reason_code, term_reason_text from bmp.raw_router where ip_addr in (select distinct ip_addr from bmp.raw_router where action = 'term')",
     "rawQuery": "select ts, action,name,ip_addr,term_reason_code, term_reason_text from bmp.raw_router where ip_addr in (select distinct ip_addr from bmp.raw_router where action = 'term')",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Flapped router",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "bmp",
     "dateTimeColDataType": "ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n\n    (intDiv(toUInt32(toStartOfInterval(ts, toIntervalSecond(1))), 1) * 1) * 1000 as t,\n    ip_addr,\n    toInt8(CAST(action, 'Enum(\\'init\\' = 1, \\'term\\' = 0)') as int8) as state\nFROM bmp.raw_router\n\nWHERE ip_addr in (\n    SELECT distinct ip_addr\n\n    FROM bmp.raw_router\n\n    WHERE action = 'term'\n)\n\ngroup by t, ip_addr, action\norder by t",
     "rawQuery": "SELECT\n\n    (intDiv(toUInt32(toStartOfInterval(ts, toIntervalSecond(1))), 1) * 1) * 1000 as t,\n    ip_addr,\n    toInt8(CAST(action, 'Enum(\\'init\\' = 1, \\'term\\' = 0)') as int8) as state\nFROM bmp.raw_router\n\nWHERE ip_addr in (\n    SELECT distinct ip_addr\n\n    FROM bmp.raw_router\n\n    WHERE action = 'term'\n)\n\ngroup by t, ip_addr, action\norder by t",
     "round": "0s",
     "table": "raw_router"
    }
   ]
  },
  {
   "title": "EVPN Changes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "prefix" }
   ],
   "targets": [
    {
     "database": "bmp",
     "dateTimeColDataType": "ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toStartOfInterval(ts + 3600*3, toIntervalMinute(1)) as t,\n    type,\n    router_ip,\n    count(type)\nFROM bmp.raw_evpn_rmt\n\nWHERE\n    $timeFilter \nGROUP BY\n    t,\n    router_ip,\n    type\nORDER BY\n    t,\n    router_ip,\n    type",
     "rawQuery": "SELECT\n    toStartOfInterval(ts + 3600*3, toIntervalMinute(1)) as t,\n    type,\n    router_ip,\n    count(type)\nFROM bmp.raw_evpn_rmt\n\nWHERE\n    ts >= toDateTime(1618723783) \nGROUP BY\n    t,\n    router_ip,\n    type\nORDER BY\n    t,\n    router_ip,\n    type",
     "round": "0s",
     "table": "raw_evpn"
    }
   ]
  },
  {
   "title": "L3VPN Changes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "prefix" }
   ],
   "targets": [
    {
     "database": "bmp",
     "dateTimeColDataType": "ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    (intDiv(toUInt32(toStartOfInterval(ts, toIntervalMinute(1))), 5) * 5) * 1000 as t,\n    action,\n    count(action)\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t, action\nORDER BY t, action\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(toStartOfInterval(ts, toIntervalMinute(1))), 5) * 5) * 1000 as t,\n    action,\n    count(action)\nFROM bmp.raw_l3vpn\n\nWHERE ts >= toDateTime(1618702015)\n\nGROUP BY t, action\nORDER BY t, action",
     "round": "0s",
     "table": "raw_l3vpn"
    }
   ]
  },
  {
   "title": "Unicast Changes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "prefix" }
   ],
   "targets": [
    {
     "database": "bmp",
     "dateTimeColDataType": "ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    (intDiv(toUInt32(toStartOfInterval(ts, toIntervalMinute(5))), 5) * 5) * 1000 as t,\n    action,\n    count(action)\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t, action\nORDER BY t, action\n",
     "round": "0s",
     "table": "raw_unicast_prefix"
    }
   ]
  }
 ]
}