{
 "title": "Top by Prefix",
 "time": { "from": "2021-04-18T06:31:01.276Z", "to": "2021-04-18T08:19:06.755Z" },
 "panels": [
  {
   "title": "Withdraws  By Router [EVPN]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "bmp",
     "dateTimeColDataType": "ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count(type) as metric,\n    rr.name as name\n  FROM bmp.raw_evpn_rmt ri\n  JOIN raw_router rr ON ri.router_ip = rr.ip_addr\n  WHERE $timeFilter and type = 'del'\n  group by t, name\n  order by t, name",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(ts), 2) * 2) * 1000 as t,\n    count(type) as metric,\n    rr.name as name\n  FROM bmp.raw_evpn_rmt ri\n  JOIN raw_router rr ON ri.router_ip = rr.ip_addr\n  WHERE ts >= toDateTime(1618760702) and type = 'del'\n  group by t, name\n  order by t, name",
     "round": "0s",
     "table": "raw_evpn"
    }
   ]
  },
  {
   "title": "Updates  By Router [EVPN]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "bmp",
     "dateTimeColDataType": "ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count(type) as metric,\n    rr.name as name\n  FROM bmp.raw_evpn_rmt ri\n  JOIN raw_router rr ON ri.router_ip = rr.ip_addr\n  WHERE $timeFilter and type = 'add'\n  group by t, name\n  order by t, name",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(ts), 2) * 2) * 1000 as t,\n    count(type) as metric,\n    rr.name as name\n  FROM bmp.raw_evpn_rmt ri\n  JOIN raw_router rr ON ri.router_ip = rr.ip_addr\n  WHERE ts >= toDateTime(1618760720) and type = 'add'\n  group by t, name\n  order by t, name",
     "round": "0s",
     "table": "raw_evpn"
    }
   ]
  },
  {
   "title": "Withdraws  By Peer [EVPN]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "bmp",
     "dateTimeColDataType": "ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count(type) as metric,\n    rr.name as name,\n    peer_addr\n  FROM bmp.raw_evpn_rmt ri\n  JOIN raw_router rr ON ri.router_ip = rr.ip_addr\n  WHERE $timeFilter and type = 'del'\n  group by t, name, peer_addr\n  order by t, name, peer_addr",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(ts), 2) * 2) * 1000 as t,\n    count(type) as metric,\n    rr.name as name,\n    peer_addr\n  FROM bmp.raw_evpn_rmt ri\n  JOIN raw_router rr ON ri.router_ip = rr.ip_addr\n  WHERE ts >= toDateTime(1618760744) and type = 'del'\n  group by t, name, peer_addr\n  order by t, name, peer_addr",
     "round": "0s",
     "table": "raw_evpn"
    }
   ]
  },
  {
   "title": "Updates  By Peer [EVPN]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "bmp",
     "dateTimeColDataType": "ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count(type) as metric,\n    rr.name as name,\n    peer_addr\n  FROM bmp.raw_evpn_rmt ri\n  JOIN raw_router rr ON ri.router_ip = rr.ip_addr\n  WHERE $timeFilter and type = 'add'\n  group by t, name, peer_addr\n  order by t, name, peer_addr",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(ts), 2) * 2) * 1000 as t,\n    count(type) as metric,\n    rr.name as name,\n    peer_addr\n  FROM bmp.raw_evpn_rmt ri\n  JOIN raw_router rr ON ri.router_ip = rr.ip_addr\n  WHERE ts >= toDateTime(1618760732) and type = 'add'\n  group by t, name, peer_addr\n  order by t, name, peer_addr",
     "round": "0s",
     "table": "raw_evpn"
    }
   ]
  },
  {
   "title": "Top Updates by Prefix [EVPN]",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "database": "bmp",
     "dateTimeColDataType": "ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT t, groupArray((ip, c)) AS groupArr\nFROM (SELECT count(type) as c, $timeSeries as t, ip\n      FROM raw_evpn_rmt\n      WHERE $timeFilter\n        and type = 'add' and ip != ''\n      GROUP BY type, ip, t order by c desc, ip limit 50)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT t, groupArray((ip, c)) AS groupArr\nFROM (SELECT count(type) as c, (intDiv(toUInt32(ts), 2) * 2) * 1000 as t, ip\n      FROM raw_evpn_rmt\n      WHERE ts >= toDateTime(1618760759)\n        and type = 'add' and ip != ''\n      GROUP BY type, ip, t order by c desc, ip limit 50)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "raw_evpn"
    }
   ]
  },
  {
   "title": "Top Withdraws by Prefix [EVPN]",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "bmp",
     "dateTimeColDataType": "ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT t, groupArray((ip, c)) AS groupArr\nFROM (SELECT count(type) as c, $timeSeries as t, ip\n      FROM raw_evpn_rmt\n      WHERE $timeFilter\n        and type = 'del' and ip != ''\n      GROUP BY type, ip, t order by c desc, ip limit 150)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT t, groupArray((ip, c)) AS groupArr\nFROM (SELECT count(type) as c, (intDiv(toUInt32(ts), 2) * 2) * 1000 as t, ip\n      FROM raw_evpn_rmt\n      WHERE ts >= toDateTime(1618760767)\n        and type = 'del' and ip != ''\n      GROUP BY type, ip, t order by c desc, ip limit 150)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "raw_evpn"
    }
   ]
  },
  {
   "title": "Top Updates by Mac [EVPN]",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "bmp",
     "dateTimeColDataType": "ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT t, groupArray((mac, c)) AS groupArr\nFROM (SELECT count(type) as c, $timeSeries as t, mac\n      FROM raw_evpn_rmt\n      WHERE $timeFilter\n        and type = 'add' and mac != ''\n      GROUP BY type, mac, t order by c desc, mac limit 20)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT t, groupArray((mac, c)) AS groupArr\nFROM (SELECT count(type) as c, (intDiv(toUInt32(ts), 2) * 2) * 1000 as t, mac\n      FROM raw_evpn_rmt\n      WHERE ts >= toDateTime(1618760779)\n        and type = 'add' and mac != ''\n      GROUP BY type, mac, t order by c desc, mac limit 20)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "raw_evpn"
    }
   ]
  },
  {
   "title": "Top Withdraws by Mac [EVPN]",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "bmp",
     "dateTimeColDataType": "ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT t, groupArray((mac, c)) AS groupArr\nFROM (SELECT count(type) as c, $timeSeries as t, mac\n      FROM raw_evpn_rmt\n      WHERE $timeFilter\n        and type = 'del' and mac != ''\n      GROUP BY type, mac, t order by c desc, mac limit 30)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT t, groupArray((mac, c)) AS groupArr\nFROM (SELECT count(type) as c, (intDiv(toUInt32(ts), 2) * 2) * 1000 as t, mac\n      FROM raw_evpn_rmt\n      WHERE ts >= toDateTime(1618760789)\n        and type = 'del' and mac != ''\n      GROUP BY type, mac, t order by c desc, mac limit 30)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "raw_evpn"
    }
   ]
  }
 ]
}